language: python
python:
  - "2.6"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get -qq install gcc libevent-1.4-2 libevent-dev
# command to install dependencies
install: pip install -q -r requirements.txt --use-mirrors
# command to run tests
script: py.test --pep8